project_id = "cpwjmfxyjtrdsnkcwruq"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[db]
port = 54322
major_version = 15

[[db.seed.sql_paths]]
path = "./seed.sql"

[db.pooler]
enabled = false
port = 54329
pool_mode = "transaction"
default_pool_size = 20
max_client_conn = 100

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"
openai_api_key = "env(OPENAI_API_KEY)"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "env(SUPABASE_AUTH_SITE_URL)"
additional_redirect_urls = ["https://127.0.0.1:54321/auth/v1/callback"]
jwt_expiry = 3600
enable_refresh_token_rotation = true
refresh_token_reuse_interval = 10
enable_signup = true
enable_anonymous_sign_ins = false
email.enable_signup = true
email.enable_confirmations = false
sms.enable_signup = true
sms.enable_confirmations = false

[auth.email]
enable_signup = true
double_confirm_changes = false
enable_confirmations = false

[auth.sms]
enable_signup = true
enable_confirmations = false
[auth.external.google]
enabled = false
client_id = ""
secret = ""
redirect_uri = ""
url = ""

[analytics]
enabled = false
port = 54327
backend = "postgres"

[functions.teams-integration]
verify_jwt = true

[functions.create-teams-meeting]
verify_jwt = true

[functions.analyze-cv]
verify_jwt = true

[functions.analyze-matching]
verify_jwt = true

[functions.send-candidat-invitation]
verify_jwt = true

[functions.send-user-invitation]
verify_jwt = true

[functions.get-auth-logs]
verify_jwt = true

[functions.get-project-info]
verify_jwt = true

[functions.configure-auth]
verify_jwt = true

[functions.send-prestataire-invitation]
verify_jwt = true